### ISSUE TITLE
Error "No memory for processing HTTP, HTTPS or SMTP query"

### ISSUE THREAD

**Issue by se38** [se38/Neo4a#7]
If too many requests are send, the error "No memory for processing HTTP, HTTPS or SMTP query" occurs.

Solution: close the http client after each request.

**Comment by itsergiu** [comment]
![image](https://user-images.githubusercontent.com/28391561/129716935-176758a0-afe3-47ca-b3a7-e936f1b631a1.png)
It works. Thank you!
